# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Elide
version:      v0.0.3
version_from: lib/Text/Elide.pm
installdirs:  site
requires:
    List::Util:                    0
    Readonly:                      0
    Smart::Comments:               0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
